services:
  app:
    image: myapp:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/SA
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
      restart_policy:
        condition: on-failure

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: SA
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '128M'
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  data:
